import { definePreset } from "./base";

/** Drafting-table look: ink blue on paper, redline annotations, hard corners. */
export const blueprint = definePreset({
  id: "blueprint",
  name: "Blueprint",
  description: "Drafting paper, ink-blue rules, redline annotations.",
  defaultMode: "light",
  colors: {
    light: {
      bg: "#eef3f7",
      bgElevated: "rgba(238, 243, 247, 0.9)",
      surface: "#ffffff",
      surfaceAlt: "#e3ebf2",
      border: "#c3d3e0",
      borderStrong: "#7d9bb3",
      fg: "#0f2b46",
      fgMuted: "#4d6b85",
      fgSubtle: "#7d95a9",
      primary: "#1d4ed8",
      primaryFg: "#f8fbff",
      accent: "#b91c1c",
      accentFg: "#fff5f5",
      ring: "#1d4ed8",
      success: "#0f766e",
      warning: "#b45309",
      danger: "#b91c1c",
      gradientFrom: "#1d4ed8",
      gradientTo: "#0f766e",
    },
    dark: {
      bg: "#071019",
      bgElevated: "rgba(7, 16, 25, 0.88)",
      surface: "#0c1a26",
      surfaceAlt: "#122636",
      border: "rgba(125, 189, 226, 0.16)",
      borderStrong: "rgba(125, 189, 226, 0.42)",
      fg: "#e2eef7",
      fgMuted: "#8fa8b8",
      fgSubtle: "#5f7a8f",
      primary: "#5b9cff",
      primaryFg: "#04121f",
      accent: "#ff7b6b",
      accentFg: "#2b0806",
      ring: "#5b9cff",
      success: "#4dd4b0",
      warning: "#f0b429",
      danger: "#ff7b6b",
      gradientFrom: "#5b9cff",
      gradientTo: "#4dd4b0",
    },
  },
  typography: {
    display: "ibm-plex-sans",
    body: "ibm-plex-sans",
    mono: "ibm-plex-mono",
    baseSize: 16,
    scaleRatio: 1.22,
    displayWeight: 600,
    bodyWeight: 400,
    displayTracking: "-0.01em",
    labelTracking: "0.12em",
    displayLeading: 1.08,
    bodyLeading: 1.62,
    labelCase: "uppercase",
    measure: 72,
  },
  shape: { radius: 2, borderWidth: 1 },
  layout: { contentWidth: 1180, gutter: 40, sectionSpacing: 88, density: "compact", align: "left" },
  effects: { grid: true, glow: false, noise: false, scanlines: false, cardStyle: "outline", navBlur: 0 },
  icons: { set: "line", strokeWidth: 1.5, size: 18 },
});
