import { definePreset } from "./base";

/** Monospace everywhere, zero radius, scanlines. Unapologetically a terminal. */
export const phosphor = definePreset({
  id: "phosphor",
  name: "Phosphor",
  description: "CRT green, monospace everything, scanlines on.",
  defaultMode: "dark",
  colors: {
    dark: {
      bg: "#01120a",
      bgElevated: "rgba(1, 18, 10, 0.92)",
      surface: "#04200f",
      surfaceAlt: "#062b16",
      border: "rgba(0, 255, 136, 0.18)",
      borderStrong: "rgba(0, 255, 136, 0.5)",
      fg: "#7dffb0",
      fgMuted: "#3faa74",
      fgSubtle: "#2a7a53",
      primary: "#00ff88",
      primaryFg: "#00190c",
      accent: "#ffb000",
      accentFg: "#1a1000",
      ring: "#00ff88",
      success: "#00ff88",
      warning: "#ffb000",
      danger: "#ff5f56",
      gradientFrom: "#00ff88",
      gradientTo: "#ffb000",
    },
    light: {
      bg: "#e6e4da",
      bgElevated: "rgba(230, 228, 218, 0.92)",
      surface: "#f0eee6",
      surfaceAlt: "#dcd9cd",
      border: "rgba(18, 32, 15, 0.22)",
      borderStrong: "rgba(18, 32, 15, 0.55)",
      fg: "#12200f",
      fgMuted: "#3d5136",
      fgSubtle: "#6b7a63",
      primary: "#0a7d3f",
      primaryFg: "#f0eee6",
      accent: "#a35c00",
      accentFg: "#fff6e6",
      ring: "#0a7d3f",
      success: "#0a7d3f",
      warning: "#a35c00",
      danger: "#a3231d",
      gradientFrom: "#0a7d3f",
      gradientTo: "#a35c00",
    },
  },
  typography: {
    display: "jetbrains-mono",
    body: "jetbrains-mono",
    mono: "jetbrains-mono",
    baseSize: 15,
    scaleRatio: 1.2,
    displayWeight: 700,
    bodyWeight: 400,
    displayTracking: "-0.01em",
    labelTracking: "0.18em",
    displayLeading: 1.15,
    bodyLeading: 1.7,
    labelCase: "uppercase",
    measure: 74,
  },
  shape: { radius: 0, borderWidth: 1 },
  layout: { contentWidth: 1000, gutter: 28, sectionSpacing: 80, density: "compact", align: "left" },
  effects: { grid: true, glow: true, noise: true, scanlines: true, cardStyle: "outline", navBlur: 0 },
  icons: { set: "emoji", strokeWidth: 1.5, size: 16 },
});
