import { definePreset } from "./base";

/** Whitespace-first. No card borders — hierarchy comes from space and weight. */
export const signal = definePreset({
  id: "signal",
  name: "Signal",
  description: "White space, black type, one electric blue. Nothing decorative.",
  defaultMode: "light",
  colors: {
    light: {
      bg: "#ffffff",
      bgElevated: "rgba(255, 255, 255, 0.92)",
      surface: "#f5f6f8",
      surfaceAlt: "#eceef1",
      border: "#e2e5ea",
      borderStrong: "#000000",
      fg: "#000000",
      fgMuted: "#54585f",
      fgSubtle: "#8c9099",
      primary: "#0047ff",
      primaryFg: "#ffffff",
      accent: "#00a67e",
      accentFg: "#ffffff",
      ring: "#0047ff",
      success: "#00a67e",
      warning: "#a35c00",
      danger: "#d61f26",
      gradientFrom: "#0047ff",
      gradientTo: "#00a67e",
    },
    dark: {
      bg: "#000000",
      bgElevated: "rgba(0, 0, 0, 0.92)",
      surface: "#0e0f11",
      surfaceAlt: "#17191c",
      border: "#26282d",
      borderStrong: "#ffffff",
      fg: "#ffffff",
      fgMuted: "#a3a7ae",
      fgSubtle: "#6d717a",
      primary: "#4d7cff",
      primaryFg: "#000816",
      accent: "#00d9a3",
      accentFg: "#002019",
      ring: "#4d7cff",
      success: "#00d9a3",
      warning: "#ffb454",
      danger: "#ff5a60",
      gradientFrom: "#4d7cff",
      gradientTo: "#00d9a3",
    },
  },
  typography: {
    display: "dm-sans",
    body: "dm-sans",
    mono: "jetbrains-mono",
    baseSize: 17,
    scaleRatio: 1.333,
    displayWeight: 700,
    bodyWeight: 400,
    displayTracking: "-0.035em",
    labelTracking: "0em",
    displayLeading: 1.02,
    bodyLeading: 1.6,
    labelCase: "none",
    measure: 62,
  },
  shape: { radius: 14, borderWidth: 1 },
  layout: { contentWidth: 1040, gutter: 40, sectionSpacing: 140, density: "spacious", align: "left" },
  effects: { grid: false, glow: false, noise: false, scanlines: false, cardStyle: "ghost", navBlur: 16 },
  icons: { set: "line", strokeWidth: 2, size: 20 },
});
